apiVersion: batch/v1
kind: Job
metadata:
  name: djangojob
spec:
  template:
    spec:
      containers:
        - name: django-job-weather
          image: kris200036/django6:latest
          command: ["bash", "-c", "/usr/src/app/entrypoint.sh"]
          env:
            - name: DJANGO_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-variable
                  key: DJANGO_ENV
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-variable
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-variable
                  key: DEBUG
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: app-variable
                  key: DJANGO_ALLOWED_HOSTS
            - name: DB_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: app-variable
                  key: DB_ENGINE
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-variable
                  key: DB_DATABASE
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-variable
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-variable
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-variable
                  key: DB_PORT
      restartPolicy: Never
  backoffLimit: 4
